# fly.toml app configuration file generated for terp-text-server on 2024-01-16T11:01:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "terp-text-server"
primary_region = "den"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
